-- Seed data for PlanMyKids

-- Insert sample programs
INSERT INTO programs (
    name, category, description, neighborhood, address,
    age_min, age_max, age_description, schedule,
    price_type, price, price_unit, price_description,
    provider_name, provider_website, contact_email, contact_phone,
    logo, images, status
) VALUES
(
    'Golden Gate Swimming Academy',
    ARRAY['swimming', 'sports'],
    'Premier swimming instruction for all ages and skill levels. Our experienced coaches focus on water safety, technique, and building confidence in the water. Small class sizes ensure personalized attention.',
    'Marina District',
    '2500 Marina Blvd, San Francisco, CA 94123',
    4, 16,
    'Preschool through High School',
    'Mon-Fri 3:30-6:00pm, Sat-Sun 9am-2pm',
    'recurring',
    150.00,
    'per month',
    '8 sessions per month. Sibling discount: 10% off',
    'Golden Gate Swim School',
    'https://example.com/ggswim',
    'info@ggswim.com',
    '(415) 555-0123',
    'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400',
    ARRAY['https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800', 'https://images.unsplash.com/photo-1438029071396-1e831a7fa6d8?w=800'],
    'active'
),
(
    'Mission Art Studio for Kids',
    ARRAY['art', 'creative'],
    'Nurture your child''s creativity with painting, drawing, sculpture, and mixed media projects. Our studio provides a fun, encouraging environment where young artists can explore and express themselves.',
    'Mission District',
    '3255 22nd St, San Francisco, CA 94110',
    5, 14,
    'Kindergarten through 8th grade',
    'Tuesdays 4-5:30pm, Thursdays 4-5:30pm, Saturdays 10am-12pm',
    'recurring',
    120.00,
    'per month',
    'All materials included. Drop-in classes available for $35/session',
    'Mission Arts Collective',
    'https://example.com/missionart',
    'hello@missionart.com',
    '(415) 555-0145',
    'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    ARRAY['https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800', 'https://images.unsplash.com/photo-1471666875520-c75081f42081?w=800'],
    'active'
),
(
    'SF Chess Champions',
    ARRAY['chess', 'academic'],
    'Learn strategic thinking and problem-solving through chess! Our program teaches children from beginners to tournament players. We focus on critical thinking, patience, and good sportsmanship.',
    'Richmond District',
    '5200 Geary Blvd, San Francisco, CA 94118',
    6, 18,
    '1st grade and up',
    'Wednesdays 3:30-5pm, Saturdays 1-3pm',
    'recurring',
    95.00,
    'per month',
    'First session free. Tournament fees separate',
    'SF Chess Academy',
    'https://example.com/sfchess',
    'coach@sfchess.com',
    '(415) 555-0167',
    'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400',
    ARRAY['https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800'],
    'active'
),
(
    'Junior Coders Club',
    ARRAY['technology', 'academic'],
    'Introduce your child to coding with Scratch, Python, and game development. Our curriculum emphasizes computational thinking and creative problem-solving in a fun, collaborative environment.',
    'SOMA',
    '123 Townsend St, San Francisco, CA 94107',
    8, 16,
    '3rd through 10th grade',
    'Mondays & Wednesdays 4-5:30pm, or Saturdays 10am-12pm',
    'recurring',
    180.00,
    'per month',
    '8 sessions per month. Laptop provided if needed',
    'Bay Area Code School',
    'https://example.com/juniorcoders',
    'info@juniorcoders.com',
    '(415) 555-0189',
    'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400',
    ARRAY['https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800', 'https://images.unsplash.com/photo-1603354350317-6f7aaa5911c5?w=800'],
    'active'
),
(
    'Sunset Soccer League',
    ARRAY['soccer', 'sports'],
    'Recreational soccer for kids of all skill levels. Our focus is on teamwork, fitness, and having fun! Professional coaches teach fundamental skills while building confidence and sportsmanship.',
    'Sunset District',
    'Golden Gate Park - West Sunset Playground',
    5, 12,
    'K-6th grade',
    'Saturdays 9am-10:30am (5-7 years), 10:30am-12pm (8-12 years)',
    'one-time',
    250.00,
    'per season',
    '10-week season. Uniform included',
    'SF Youth Soccer',
    'https://example.com/sunsetsoccer',
    'register@sfyouthsoccer.com',
    '(415) 555-0201',
    'https://images.unsplash.com/photo-1473163928189-364b2c4e1135?w=400',
    ARRAY['https://images.unsplash.com/photo-1473163928189-364b2c4e1135?w=800', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800'],
    'active'
),
(
    'Young Musicians Conservatory',
    ARRAY['music', 'creative'],
    'Private and group music lessons for piano, violin, guitar, and voice. Our experienced instructors tailor lessons to each student''s interests and goals, preparing students for recitals and competitions.',
    'Noe Valley',
    '4000 24th St, San Francisco, CA 94114',
    5, 18,
    'All ages',
    'Flexible scheduling Mon-Sat',
    'recurring',
    200.00,
    'per month',
    '4 private 30-min lessons or 4 group 60-min lessons',
    'SF Conservatory Junior Program',
    'https://example.com/youngmusicians',
    'admissions@youngmusicians.com',
    '(415) 555-0223',
    'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400',
    ARRAY['https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800', 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800'],
    'active'
),
(
    'Martial Arts for Kids - Taekwondo',
    ARRAY['martial-arts', 'sports'],
    'Traditional Taekwondo instruction emphasizing discipline, respect, and self-confidence. Students learn self-defense, improve fitness, and work toward belt advancement in a supportive environment.',
    'Castro',
    '4567 18th St, San Francisco, CA 94114',
    5, 15,
    'Ages 5-15',
    'Mon/Wed/Fri 4-5pm (beginners), 5-6pm (intermediate/advanced)',
    'recurring',
    135.00,
    'per month',
    'Unlimited classes. Uniform $50 (one-time)',
    'SF Taekwondo Academy',
    'https://example.com/sftkd',
    'master@sftkd.com',
    '(415) 555-0245',
    'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400',
    ARRAY['https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800'],
    'active'
),
(
    'SF Public Library STEM Workshops',
    ARRAY['science', 'academic', 'technology'],
    'Free hands-on STEM workshops exploring robotics, engineering, and environmental science. Each session includes experiments, projects, and take-home materials. Part of the library''s youth enrichment program.',
    'Mission District',
    'Mission Branch Library, 300 Bartlett St, San Francisco, CA 94110',
    7, 13,
    'Ages 7-13',
    'Every other Saturday, 2-3:30pm',
    'free',
    0,
    null,
    'Free! Registration required (limited spots)',
    'San Francisco Public Library',
    'https://example.com/sfpl',
    'youth@sfpl.org',
    '(415) 555-0267',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400',
    ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800'],
    'active'
);

-- Insert sample reviews
INSERT INTO reviews (program_id, reviewer_name, reviewer_email, rating, comment, status) VALUES
(
    (SELECT id FROM programs WHERE name = 'Golden Gate Swimming Academy' LIMIT 1),
    'Sarah Martinez',
    'sarah.m@example.com',
    5,
    'My daughter went from being afraid of water to swimming confidently in just 3 months! The instructors are patient and encouraging. Highly recommend!',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Golden Gate Swimming Academy' LIMIT 1),
    'John Chen',
    'jchen@example.com',
    4,
    'Great program with experienced coaches. My son has improved so much. Only downside is parking can be difficult in the Marina.',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Mission Art Studio for Kids' LIMIT 1),
    'Emily Rodriguez',
    'emily.r@example.com',
    5,
    'Such a creative and welcoming space! The teachers really know how to bring out each child''s artistic side. My kids look forward to class every week.',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'SF Chess Champions' LIMIT 1),
    'Michael Wong',
    'mwong@example.com',
    5,
    'This program has been amazing for my son''s critical thinking skills. The coaches are knowledgeable and patient. He recently won his first tournament!',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Junior Coders Club' LIMIT 1),
    'Lisa Patel',
    'lisa.patel@example.com',
    5,
    'My daughter is obsessed with coding now! The curriculum is well-structured and the projects are engaging. Worth every penny.',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Sunset Soccer League' LIMIT 1),
    'David Kim',
    'dkim@example.com',
    4,
    'Great recreational league with a focus on fun over competition. Coaches are volunteers but very dedicated. Fields in Golden Gate Park are beautiful!',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Young Musicians Conservatory' LIMIT 1),
    'Amanda Foster',
    'amanda.f@example.com',
    5,
    'Outstanding music instruction! My son has been taking piano for 2 years and the progress is remarkable. Teachers are professional and encouraging.',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'Martial Arts for Kids - Taekwondo' LIMIT 1),
    'Robert Taylor',
    'rtaylor@example.com',
    5,
    'This school has helped my daughter with discipline and confidence. Master Kim is excellent with kids. She earned her yellow belt last month!',
    'approved'
),
(
    (SELECT id FROM programs WHERE name = 'SF Public Library STEM Workshops' LIMIT 1),
    'Maria Gonzalez',
    'maria.g@example.com',
    4,
    'Amazing that this is free! My kids have learned so much about robotics and science. Spots fill up fast so register early.',
    'approved'
);
